apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-kotak-deployment
spec:
  replicas: 2  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs-container
        image: uzairbagwan/node-app:latest
        ports:
        - containerPort: 3000

